language: node_js
sudo: false
cache:
  directories:
    - node_modules
dist: trusty
node_js:
  - '7.3.0'
branches:
  only:
  - master
before_script:
 - wget http://oidamo.de/compact.tar
 - mkdir -p src/assets/img/gallery/
 - mv compact.tar src/assets/img/gallery/
 - pushd src/assets/img/gallery/ && tar xvf compact.tar --strip-components 1 && popd
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - npm run build -- --prod --aot
 - npm run e2e
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
