language: node_js
sudo: false
cache:
  directories:
    - node
dist: trusty
node_js:
  - '7.3.0'
branches:
  only:
  - master
before_install:
 - npm install -g @angular/cli@latest
before_script:
 - wget http://oidamo.de/compact.tar
 - mkdir -p /home/travis/build/BenjaminBrandmeier/angular2-image-gallery/src/assets/img/gallery/
 - mv compact.tar /home/travis/build/BenjaminBrandmeier/angular2-image-gallery/src/assets/img/gallery/
 - pushd /home/travis/build/BenjaminBrandmeier/angular2-image-gallery/src/assets/img/gallery/ && tar xvf compact.tar --strip-components 1 && popd
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - npm run build
 - npm run e2e
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
